name: Valgrind check

on:
  schedule:
    # every night at one
    - cron: '0 1 * * *'
  # or on a manual trigger
  workflow_dispatch:

env:
  IMAGE_NAME: localhost:5000/orion-ld-test:latest

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile-test
          tags: ${{ env.IMAGE_NAME }}
          outputs: type=docker,dest=/tmp/test-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-image
          path: /tmp/test-image.tar

  valgrind-suite:
    runs-on: ubuntu-18.04
    needs: build-test-image

    services:
      mosquitto:
        image: eclipse-mosquitto:1.6
        ports:
          - 1883:1883
          - 9001:9001
      postgres:
        image: postgis/postgis:12-3.1-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
      context-server:
        image: wistefan/context-server:0.2.0
        env:
          MEMORY_ENABLED: true
        ports:
          - 7080:8080

    strategy:
      fail-fast: false
      matrix:
        # since the test are very slow, we use a very high degree of parallelism
        testIndexToStartAt: [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100, 1150, 1200, 1250, 1300, 1350, 1400, 1450, 1500, 1550]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: test-image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/test-image.tar

      - name: Execute valgrind
        run: |
          docker run --rm --network host -v $(pwd):/opt/orion -e CB_FT_VERBOSE=true -e ORIONLD_CACHED_CONTEXT_DIRECTORY=/opt/orion/ldcontexts -e CB_FT_VERBOSE=ON  --entrypoint bash ${{ env.IMAGE_NAME }} /opt/orion/test/valgrind/valgrindTestSuite.sh -fromIx ${{ matrix.testIndexToStartAt }} -toIx ${{ matrix.testIndexToStartAt }}+49
